---
title: "Findings"
title-block-banner: TRUE
fig-width: 7
fig-height: 5
warning: FALSE
error: TRUE
echo: FALSE
message: FALSE
---

```{r, Data Inputs}
#| include: FALSE
library(cpaltemplates)
library(tidycensus)
library(tidyverse)
library(rio)
library(sf)
library(googlesheets4)

libDB <- "C:/Users/micha/CPAL Dropbox/"

courtobs <- read_sheet(ss = "https://docs.google.com/spreadsheets/d/1O9P06SgvZ_nRGc64W2OsSjyX9iCS_LkcsG9087HNTuk",
                               sheet = "Form Responses 1") %>%
  janitor::clean_names(.) %>%
  rename("timeStamp"="timestamp",
         "observer"="observer",
         "observationDate"="date_of_observation",
         "jpCourt"="justice_of_the_peace_court",
         "docketStart"="docket_start_time_please_indicate_what_time_the_judge_called_the_first_case_on_the_docket_use_format_hh_mm_and_specify_am_or_pm_e_g_09_32_am",
         "docketEnd"="docket_end_time_please_indicate_the_time_the_judge_finished_hearing_the_last_case_on_the_docket_use_format_hh_mm_and_specify_am_or_pm_e_g_12_34_pm",
         "caseNumber"="case_number",
         "caseType"="is_this_a_commercial_or_residential_eviction_case",
         "plaintiffName"="plaintiff_landlord_name",
         "plaintiffDesignee"="did_the_plaintiff_landlord_or_their_designee_like_a_property_manager_appear",
         "plaintiffRep"="did_the_plaintiff_landlord_have_additional_representation_of_some_kind",
         "defName"="defendant_tenant_name",
         "defAppear"="did_the_defendant_tenant_appear",
         "defRep"="did_the_defendant_tenant_have_additional_representation_of_some_kind",
         "evicReason"="reason_for_eviction_select_multiple_if_applicable",
         "totalOwned"="total_amount_owed_please_indicate_the_total_amount_that_the_judge_or_landlord_states_is_owed_include_the_sum_of_rent_or_damages_owed_plus_court_costs_use_format_xxxx_xx_for_example_1234_50",
         "noticeVacate"="was_there_any_discussion_about_the_notice_to_vacate_ntv",
         "noticeConfirm"="if_yes_did_the_judge_confirm_the_ntv",
         "jpRuled"="the_jp_ruled_in_favor_of",
         "outcomeOther"="if_you_selected_other_please_specify_the_outcome_of_the_case_below",
         "otherNotes"="additional_case_notes"
)

#dallas county evictions dataset
evictions <- rio::import(paste0(libDB, "Data Library/Dallas County/Eviction Records/Data/Dallas County Eviction Master/EvictionRecords_Master.csv"))

#court observation dates
startDate <- min(courtobs$observationDate, na.rm = TRUE)
endDate <- max(courtobs$observationDate, na.rm = TRUE)

#total days between start and end of data
totdays <- difftime(endDate, startDate, "days") %>%
  as.numeric()

#evictions by year
# most recent year (this year)
totevic1 <- evictions %>%
  filter(filed_date >= as.Date("2022-11-01") & filed_date < as.Date("2023-04-20"))

#last year
totevic2 <- evictions %>%
  filter(filed_date >= as.Date("2021-11-01") & filed_date < as.Date("2022-04-20"))

# oldest year (two years ago)
totevic3 <- evictions %>%
  filter(filed_date >= as.Date("2020-11-01") & filed_date < as.Date("2021-04-20"))

#average evictions by day, this year
avgevic1 <- round(nrow(totevic1)/totdays, digits = 1)

#average evictions by day, last year
avgevic2 <- round(nrow(totevic2)/totdays, digits = 1)

#percent change in evictions this year
chgevic1 <- round(((nrow(totevic1)-nrow(totevic2))/nrow(totevic2))*100, digits = 1)
#percent change in evictions last year
chgevic2 <- round(((nrow(totevic1)-nrow(totevic3))/nrow(totevic3))*100, digits = 1)

#average evictions by month in the last 5 years
evicMonths <- evictions %>%
  filter(filed_date >= as.Date("2019-01-01")) %>%
  group_by(lubridate::year(filed_date), lubridate::month(filed_date)) %>%
  summarize(totevic = n()) %>%
  rename(yearFiled = 1,
         monthFiled = 2) %>%
  mutate(dateFiled = as.Date(paste0(yearFiled, "-", monthFiled, "-01"))) %>%
  ungroup(.)

#month with highest number of evictions in the last 5 years
highestMonth <- evicMonths %>%
  filter(totevic == max(totevic))

#total number of SMU students observing cases
smuStudents <- n_distinct(courtobs$observer)

#total number of cases observed
totObsCases <- courtobs %>%
  nrow(.)

#total number of cases scheduled by court in time period of court observations
obsCourt <- evictions %>%
  filter(appearance_date >= as.Date("2022-11-01") & appearance_date < as.Date("2023-04-20")) %>%
  group_by(court) %>%
  summarize(totEvic = n()) %>%
  filter(court %in% c("Court  1-1",
                     "Court  1-2",
                     "Court  3-1",
                     "Court  3-2",
                     "Court  4-1",
                     "Court  5-1")) %>%
  ungroup(.)

#total number of cases observed by volunteers in observation period by court
jpCasesObs <- courtobs %>%
  group_by(jpCourt) %>%
  summarize(obsCases = n()) %>%
  mutate(perObsCases = obsCases/totObsCases,
         court = ifelse(jpCourt == "1-1", "Court  1-1",
                     ifelse(jpCourt == "1-2", "Court  1-2",
                     ifelse(jpCourt == "3-1", "Court  3-1",
                     ifelse(jpCourt == "3-2", "Court  3-2",
                     ifelse(jpCourt == "4-1", "Court  4-1",
                     ifelse(jpCourt == "5-1", "Court  5-1", "Other"))))))) %>%
  ungroup(.) %>%
  left_join(., obsCourt) %>%
  mutate(perAllCases = obsCases/totEvic)

#cases observed compared to entire county
jpCasesCty <- jpCasesObs %>%
  filter(jpCourt %in% c("1-1", "3-1", "5-1")) %>%
  summarize(obsCases = sum(obsCases),
            totEvic = sum(totEvic)) %>%
  mutate(perAllCases = round(obsCases/totEvic, digits = 3))

#case outcome by party filed in favor of by jp court
caseOutcome <- courtobs %>%
  filter(!is.na(jpCourt)) %>%
  mutate(outcomeParty = ifelse(str_detect(jpRuled, "Plaintiff"), "Plaintiff",
                                          ifelse(str_detect(jpRuled, "Defendant"), "Defendant", "Other"))) %>%
  group_by(jpCourt, outcomeParty) %>%
  summarize(count = n()) %>%
  pivot_wider(names_from = outcomeParty, values_from = count, values_fill = 0, names_prefix = "result") %>%
  ungroup(.) %>%
  mutate(perPlain = resultPlaintiff/(resultDefendant+resultPlaintiff+resultOther),
         perDef = resultDefendant/(resultDefendant+resultPlaintiff+resultOther))

#case outcomes when defendant is present for all cases observed
defPresent <- courtobs %>%
  filter(!is.na(jpCourt),
         defAppear != "Unknown") %>%
  group_by(defAppear, jpRuled) %>%
  summarize(count = n()) %>%
  ungroup(.) %>%
  pivot_wider(names_from = defAppear, values_from = count, values_fill = 0) %>%
  mutate(NoPer = No/sum(No),
         YesPer = Yes/sum(Yes))

#case outcomes when defendant has representation for all cases observed
defRepresent <- courtobs %>%
  filter(!is.na(jpCourt)) %>%
  group_by(defRep, jpRuled) %>%
  summarize(count = n()) %>%
  ungroup(.) %>%
  pivot_wider(names_from = defRep, values_from = count, values_fill = 0)

#eviction reason
evicReason <- courtobs %>%
  filter(!is.na(jpCourt)) %>%
  mutate(evicClean = ifelse(str_detect(evicReason, ","), "Multiple Reasons", evicReason)) %>%
  group_by(jpCourt, evicClean) %>%
  summarize(count = n())
```

# CONTEXT

**Eviction has a devastating impact on families:** involuntary displacement leads to greater material
hardship, poorer health and avoidable healthcare costs for children and their mothers, negative
impacts on children’s academic achievement, and greater depression and parental stress. Eviction
disproportionately impacts communities of color, and the likelihood of receiving an eviction judgment is
highest for mothers with children.

**Between November 1, 2022 and April 20, 2023, 18,485 evictions have been filed in Dallas County, an average of `r avgevic1` per day.**
This represents a `r paste0(chgevic1, "%")` change over the same time period in 2022 and a `r paste0(chgevic2, "%")` change over the same
time period in 2021. Evictions have been on the rise since the end of the CDC Eviction Moratorium in August 2021, and Dallas County realized its highest one-month filing total in at least five years in **August 2022**, with **`r formatC(highestMonth$totevic, big.mark = ",")`** evictions filed.

# COURT PROCESS

```{mermaid}
flowchart LR
  A[Eviction Filed by Landlord] --> B(Tenant Receives Notice)
  B --> C{Case Date within X days}
  C --> D[Hearing Held]
  D --> E[Case Outcome]
  E --> F{Filed in Favor of Landlord}
  E --> G{Filed in Favor of Tenant}
```

# PROJECT BACKGROUND

In spring 2021, the Child Poverty Action Lab (CPAL) launched a court observation project to collect,
analyze, and share eviction-related data not otherwise reported publicly. Eviction docket court observation
has been ongoing since, with the purpose of (1) improving local understanding of how eviction unfolds,
(2) uncovering barriers/challenges for tenants and landlords, and (3) identifying ways to better support
tenants and landlords upstream of an eviction hearing. Observation first began in Dallas County Justice
of the Peace Court 1-1 and expanded to Dallas County Justice of the Peace Courts 3-1 and 5-1 in 2022.

# COURT OBSERVATION PROTOCOL

The court observation project is powered by volunteer observers who attend eviction dockets in-person,
take notes as eviction cases are heard, and then enter the data digitally for CPAL analysis. Since late
2021, volunteer observers have all been SMU Dedman School of Law students, primarily in their second
or third year of law school, volunteering as part of a class requirement or to fulfill public service hours.
CPAL staff on-board volunteer observers through a two-part training: the first is an introductory online
session to explain the eviction process, and the second is an onsite session at a Justice of the Peace
court focused on data collection through observation.

Once trained, volunteers sign-up for dockets to observe using a digital scheduler. Volunteers select
dockets to observe based on their availability, so observed cases do not represent a random selection.
During docket observations, volunteers take notes on cases heard using a paper template and then enter
the data afterwards into a Google Form created and managed by CPAL. Before analysis and reporting,
CPAL reviews and cleans the data, as needed.
