---
title: "Report Context"
title-block-banner: TRUE
fig-width: 7
fig-height: 5
warning: FALSE
error: TRUE
echo: FALSE
message: FALSE
---

# SUMMER 2023 FINDINGS

From June 1, 2022 through August 5, 2022, nine SMU Law student volunteers observed
1,135 cases: 464 in Justice of the Peace Court 1-1, 344 in Justice of the Peace Court
3-1, and 327 in Justice of the Peace Court 5-1. The 1,135 observed cases represent 32%
coverage of all initially scheduled hearings in 1-1, 3-1, and 5-1.

+-----------+--------------------------------------------------+--------------------------------------------------+-------------+------------+
| Coverage  | {{< fa house-chimney size=lg title="Housing" >}} | {{< fa house-chimney size=lg title="Housing" >}} | Chart 3     | Total      |
+:==========+:================================================:+:================================================:+:===========:+:==========:+
|   12 <br> |                                      12 <br>     |   12            <br>                             |     12 <br>  |  12 <br>  |
|   12 <br> |                                      12 <br>     |   12            <br>                             |     12 <br>  |  12 <br>  |
|   12 <br> |                                      12 <br>     |   12            <br>                             |     12 <br>  |  12 <br>  |
+-----------+--------------------------------------------------+--------------------------------------------------+-------------+------------+

*The ‘scheduled hearings’ indicator was calculated based on the hearing date set at the time of the eviction filing. If a hearing date was
subsequently rescheduled for a date later than August 5, then the case is still included here in the ‘scheduled hearings’ count. Some scheduled
hearings may have been dismissed in advance of the docket, so ‘coverage’ here is likely an underrepresentation of cases observed relative to the
number of cases heard during a docket.

**Across the 1,135 observed cases, we found:**

+-----------+--------------------------------------------------+--------------------------------------------------+-------------+------------+
| Coverage  | {{< fa house-chimney size=lg title="Housing" >}} | {{< fa house-chimney size=lg title="Housing" >}} | Chart 3     | Total      |
+:==========+:================================================:+:================================================:+:===========:+:==========:+
|   12 <br> |                                      12 <br>     |   12            <br>                             |     12 <br>  |  12 <br>  |
|   12 <br> |                                      12 <br>     |   12            <br>                             |     12 <br>  |  12 <br>  |
|   12 <br> |                                      12 <br>     |   12            <br>                             |     12 <br>  |  12 <br>  |
+-----------+--------------------------------------------------+--------------------------------------------------+-------------+------------+

*The reason for an eviction case might be unknown if a default judgment was awarded to a landlord and the facts of the case were not
discussed. Reasons are rounded to the nearest whole number, so totals may not equal 100%.

{{< fa house-chimney size=lg title="Housing" >}} **Why this matters**: In Dallas County, millions of dollars for rent relief have been available throughout the
pandemic. Eviction cases due to nonpayment of rent might have been remedied had the renter and landlord
been aware of and able to easily access rent relief programs.
